image: php:5.5

variables:
  # Configure mysql environment variables (https://hub.docker.com/r/_/mysql/)
  MYSQL_DATABASE: miraath
  MYSQL_ROOT_PASSWORD: password

services:
  - mysql:latest

before_script:
  - apt-get -qq update
  - apt-get -qq -y --no-install-recommends install apt-utils
  - apt-get -qq -y install mysql-client unzip git
  - docker-php-ext-install pdo_mysql
  - mysql -u root --password="${MYSQL_ROOT_PASSWORD}" --host=mysql -e 'CREATE DATABASE $MYSQL_DATABASE;'
  - mysql -u root --password="${MYSQL_ROOT_PASSWORD}" --host=mysql "${MYSQL_DATABASE}" < db-export/mir_db.sql
  - echo "DB_USER=root" > .env
  - echo "DB_NAME=miraath" >> .env
  - echo "DB_PASSWORD=password" >> .env
  - echo "DB_HOST=mysql" >> .env
  - curl --silent --show-error https://getcomposer.org/installer | php
  # - chmod +x composer.phar
  - mv composer.phar /usr/local/bin/composer
  - composer install --prefer-dist
  # - export DB_USER=root DB_PASSWORD="${MYSQL_ROOT_PASSWORD}" DB_NAME=${MYSQL_DATABASE} DB_HOST=mysql

test:app:
  script:
  - vendor/bin/ocular code-coverage:upload --format=php-clover build/logs/clover.xml --repository miraath/mir-migration

# test:db:
#   script:
#   - echo "SHOW TABLES;" | mysql --user=root --password="${MYSQL_ROOT_PASSWORD}" --host=mysql "${MYSQL_DATABASE}"

# notifications:
#   slack: miraath:A34LlZZ3Fqvc1YE45TS6WXsy
